/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRequestPasswordRouteImport } from './routes/_auth/request-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as SeasonSlugLegSlugRouteRouteImport } from './routes/$seasonSlug/$legSlug/route'
import { Route as SeasonSlugLegSlugIndexRouteImport } from './routes/$seasonSlug/$legSlug/index'
import { Route as SeasonSlugLegSlugVotingIndexRouteImport } from './routes/$seasonSlug/$legSlug/voting/index'
import { Route as SeasonSlugLegSlugVideosIndexRouteImport } from './routes/$seasonSlug/$legSlug/videos/index'
import { Route as SeasonSlugLegSlugStatsIndexRouteImport } from './routes/$seasonSlug/$legSlug/stats/index'
import { Route as SeasonSlugLegSlugStandingsIndexRouteImport } from './routes/$seasonSlug/$legSlug/standings/index'
import { Route as SeasonSlugLegSlugScheduleIndexRouteImport } from './routes/$seasonSlug/$legSlug/schedule/index'
import { Route as SeasonSlugLegSlugQuizIndexRouteImport } from './routes/$seasonSlug/$legSlug/quiz/index'
import { Route as SeasonSlugLegSlugGalleryIndexRouteImport } from './routes/$seasonSlug/$legSlug/gallery/index'
import { Route as SeasonSlugLegSlugClubsIndexRouteImport } from './routes/$seasonSlug/$legSlug/clubs/index'
import { Route as SeasonSlugLegSlugScheduleFixtureIdRouteRouteImport } from './routes/$seasonSlug/$legSlug/schedule/$fixtureId/route'
import { Route as SeasonSlugLegSlugClubsClubSlugRouteRouteImport } from './routes/$seasonSlug/$legSlug/clubs/$clubSlug/route'
import { Route as SeasonSlugLegSlugVotingVoteIdIndexRouteImport } from './routes/$seasonSlug/$legSlug/voting/$voteId/index'
import { Route as SeasonSlugLegSlugVideosVideoIdIndexRouteImport } from './routes/$seasonSlug/$legSlug/videos/$videoId/index'
import { Route as SeasonSlugLegSlugScheduleFixtureIdIndexRouteImport } from './routes/$seasonSlug/$legSlug/schedule/$fixtureId/index'
import { Route as SeasonSlugLegSlugQuizQuizIdIndexRouteImport } from './routes/$seasonSlug/$legSlug/quiz/$quizId/index'
import { Route as SeasonSlugLegSlugClubsClubSlugIndexRouteImport } from './routes/$seasonSlug/$legSlug/clubs/$clubSlug/index'
import { Route as SeasonSlugLegSlugScheduleFixtureIdStatsRouteImport } from './routes/$seasonSlug/$legSlug/schedule/$fixtureId/stats'
import { Route as SeasonSlugLegSlugScheduleFixtureIdLineupsRouteImport } from './routes/$seasonSlug/$legSlug/schedule/$fixtureId/lineups'
import { Route as SeasonSlugLegSlugScheduleFixtureIdH2hRouteImport } from './routes/$seasonSlug/$legSlug/schedule/$fixtureId/h2h'
import { Route as SeasonSlugLegSlugQuizQuizIdLeaderboardRouteImport } from './routes/$seasonSlug/$legSlug/quiz/$quizId/leaderboard'
import { Route as SeasonSlugLegSlugClubsClubSlugStatsRouteImport } from './routes/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
import { Route as SeasonSlugLegSlugClubsClubSlugFixturesRouteImport } from './routes/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRequestPasswordRoute = AuthRequestPasswordRouteImport.update({
  id: '/request-password',
  path: '/request-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const SeasonSlugLegSlugRouteRoute = SeasonSlugLegSlugRouteRouteImport.update({
  id: '/$seasonSlug/$legSlug',
  path: '/$seasonSlug/$legSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonSlugLegSlugIndexRoute = SeasonSlugLegSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeasonSlugLegSlugRouteRoute,
} as any)
const SeasonSlugLegSlugVotingIndexRoute =
  SeasonSlugLegSlugVotingIndexRouteImport.update({
    id: '/voting/',
    path: '/voting/',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugVideosIndexRoute =
  SeasonSlugLegSlugVideosIndexRouteImport.update({
    id: '/videos/',
    path: '/videos/',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugStatsIndexRoute =
  SeasonSlugLegSlugStatsIndexRouteImport.update({
    id: '/stats/',
    path: '/stats/',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugStandingsIndexRoute =
  SeasonSlugLegSlugStandingsIndexRouteImport.update({
    id: '/standings/',
    path: '/standings/',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugScheduleIndexRoute =
  SeasonSlugLegSlugScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugQuizIndexRoute =
  SeasonSlugLegSlugQuizIndexRouteImport.update({
    id: '/quiz/',
    path: '/quiz/',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugGalleryIndexRoute =
  SeasonSlugLegSlugGalleryIndexRouteImport.update({
    id: '/gallery/',
    path: '/gallery/',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugClubsIndexRoute =
  SeasonSlugLegSlugClubsIndexRouteImport.update({
    id: '/clubs/',
    path: '/clubs/',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugScheduleFixtureIdRouteRoute =
  SeasonSlugLegSlugScheduleFixtureIdRouteRouteImport.update({
    id: '/schedule/$fixtureId',
    path: '/schedule/$fixtureId',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugClubsClubSlugRouteRoute =
  SeasonSlugLegSlugClubsClubSlugRouteRouteImport.update({
    id: '/clubs/$clubSlug',
    path: '/clubs/$clubSlug',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugVotingVoteIdIndexRoute =
  SeasonSlugLegSlugVotingVoteIdIndexRouteImport.update({
    id: '/voting/$voteId/',
    path: '/voting/$voteId/',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugVideosVideoIdIndexRoute =
  SeasonSlugLegSlugVideosVideoIdIndexRouteImport.update({
    id: '/videos/$videoId/',
    path: '/videos/$videoId/',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugScheduleFixtureIdIndexRoute =
  SeasonSlugLegSlugScheduleFixtureIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SeasonSlugLegSlugScheduleFixtureIdRouteRoute,
  } as any)
const SeasonSlugLegSlugQuizQuizIdIndexRoute =
  SeasonSlugLegSlugQuizQuizIdIndexRouteImport.update({
    id: '/quiz/$quizId/',
    path: '/quiz/$quizId/',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugClubsClubSlugIndexRoute =
  SeasonSlugLegSlugClubsClubSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SeasonSlugLegSlugClubsClubSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugScheduleFixtureIdStatsRoute =
  SeasonSlugLegSlugScheduleFixtureIdStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => SeasonSlugLegSlugScheduleFixtureIdRouteRoute,
  } as any)
const SeasonSlugLegSlugScheduleFixtureIdLineupsRoute =
  SeasonSlugLegSlugScheduleFixtureIdLineupsRouteImport.update({
    id: '/lineups',
    path: '/lineups',
    getParentRoute: () => SeasonSlugLegSlugScheduleFixtureIdRouteRoute,
  } as any)
const SeasonSlugLegSlugScheduleFixtureIdH2hRoute =
  SeasonSlugLegSlugScheduleFixtureIdH2hRouteImport.update({
    id: '/h2h',
    path: '/h2h',
    getParentRoute: () => SeasonSlugLegSlugScheduleFixtureIdRouteRoute,
  } as any)
const SeasonSlugLegSlugQuizQuizIdLeaderboardRoute =
  SeasonSlugLegSlugQuizQuizIdLeaderboardRouteImport.update({
    id: '/quiz/$quizId/leaderboard',
    path: '/quiz/$quizId/leaderboard',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugClubsClubSlugStatsRoute =
  SeasonSlugLegSlugClubsClubSlugStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => SeasonSlugLegSlugClubsClubSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugClubsClubSlugFixturesRoute =
  SeasonSlugLegSlugClubsClubSlugFixturesRouteImport.update({
    id: '/fixtures',
    path: '/fixtures',
    getParentRoute: () => SeasonSlugLegSlugClubsClubSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$seasonSlug/$legSlug': typeof SeasonSlugLegSlugRouteRouteWithChildren
  '/register': typeof AuthRegisterRoute
  '/request-password': typeof AuthRequestPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify': typeof AuthVerifyRoute
  '/$seasonSlug/$legSlug/': typeof SeasonSlugLegSlugIndexRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug': typeof SeasonSlugLegSlugClubsClubSlugRouteRouteWithChildren
  '/$seasonSlug/$legSlug/schedule/$fixtureId': typeof SeasonSlugLegSlugScheduleFixtureIdRouteRouteWithChildren
  '/$seasonSlug/$legSlug/clubs/': typeof SeasonSlugLegSlugClubsIndexRoute
  '/$seasonSlug/$legSlug/gallery/': typeof SeasonSlugLegSlugGalleryIndexRoute
  '/$seasonSlug/$legSlug/quiz/': typeof SeasonSlugLegSlugQuizIndexRoute
  '/$seasonSlug/$legSlug/schedule/': typeof SeasonSlugLegSlugScheduleIndexRoute
  '/$seasonSlug/$legSlug/standings/': typeof SeasonSlugLegSlugStandingsIndexRoute
  '/$seasonSlug/$legSlug/stats/': typeof SeasonSlugLegSlugStatsIndexRoute
  '/$seasonSlug/$legSlug/videos/': typeof SeasonSlugLegSlugVideosIndexRoute
  '/$seasonSlug/$legSlug/voting/': typeof SeasonSlugLegSlugVotingIndexRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures': typeof SeasonSlugLegSlugClubsClubSlugFixturesRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug/stats': typeof SeasonSlugLegSlugClubsClubSlugStatsRoute
  '/$seasonSlug/$legSlug/quiz/$quizId/leaderboard': typeof SeasonSlugLegSlugQuizQuizIdLeaderboardRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h': typeof SeasonSlugLegSlugScheduleFixtureIdH2hRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups': typeof SeasonSlugLegSlugScheduleFixtureIdLineupsRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/stats': typeof SeasonSlugLegSlugScheduleFixtureIdStatsRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug/': typeof SeasonSlugLegSlugClubsClubSlugIndexRoute
  '/$seasonSlug/$legSlug/quiz/$quizId/': typeof SeasonSlugLegSlugQuizQuizIdIndexRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/': typeof SeasonSlugLegSlugScheduleFixtureIdIndexRoute
  '/$seasonSlug/$legSlug/videos/$videoId/': typeof SeasonSlugLegSlugVideosVideoIdIndexRoute
  '/$seasonSlug/$legSlug/voting/$voteId/': typeof SeasonSlugLegSlugVotingVoteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof AuthRegisterRoute
  '/request-password': typeof AuthRequestPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify': typeof AuthVerifyRoute
  '/$seasonSlug/$legSlug': typeof SeasonSlugLegSlugIndexRoute
  '/$seasonSlug/$legSlug/clubs': typeof SeasonSlugLegSlugClubsIndexRoute
  '/$seasonSlug/$legSlug/gallery': typeof SeasonSlugLegSlugGalleryIndexRoute
  '/$seasonSlug/$legSlug/quiz': typeof SeasonSlugLegSlugQuizIndexRoute
  '/$seasonSlug/$legSlug/schedule': typeof SeasonSlugLegSlugScheduleIndexRoute
  '/$seasonSlug/$legSlug/standings': typeof SeasonSlugLegSlugStandingsIndexRoute
  '/$seasonSlug/$legSlug/stats': typeof SeasonSlugLegSlugStatsIndexRoute
  '/$seasonSlug/$legSlug/videos': typeof SeasonSlugLegSlugVideosIndexRoute
  '/$seasonSlug/$legSlug/voting': typeof SeasonSlugLegSlugVotingIndexRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures': typeof SeasonSlugLegSlugClubsClubSlugFixturesRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug/stats': typeof SeasonSlugLegSlugClubsClubSlugStatsRoute
  '/$seasonSlug/$legSlug/quiz/$quizId/leaderboard': typeof SeasonSlugLegSlugQuizQuizIdLeaderboardRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h': typeof SeasonSlugLegSlugScheduleFixtureIdH2hRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups': typeof SeasonSlugLegSlugScheduleFixtureIdLineupsRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/stats': typeof SeasonSlugLegSlugScheduleFixtureIdStatsRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug': typeof SeasonSlugLegSlugClubsClubSlugIndexRoute
  '/$seasonSlug/$legSlug/quiz/$quizId': typeof SeasonSlugLegSlugQuizQuizIdIndexRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId': typeof SeasonSlugLegSlugScheduleFixtureIdIndexRoute
  '/$seasonSlug/$legSlug/videos/$videoId': typeof SeasonSlugLegSlugVideosVideoIdIndexRoute
  '/$seasonSlug/$legSlug/voting/$voteId': typeof SeasonSlugLegSlugVotingVoteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/$seasonSlug/$legSlug': typeof SeasonSlugLegSlugRouteRouteWithChildren
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/request-password': typeof AuthRequestPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/$seasonSlug/$legSlug/': typeof SeasonSlugLegSlugIndexRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug': typeof SeasonSlugLegSlugClubsClubSlugRouteRouteWithChildren
  '/$seasonSlug/$legSlug/schedule/$fixtureId': typeof SeasonSlugLegSlugScheduleFixtureIdRouteRouteWithChildren
  '/$seasonSlug/$legSlug/clubs/': typeof SeasonSlugLegSlugClubsIndexRoute
  '/$seasonSlug/$legSlug/gallery/': typeof SeasonSlugLegSlugGalleryIndexRoute
  '/$seasonSlug/$legSlug/quiz/': typeof SeasonSlugLegSlugQuizIndexRoute
  '/$seasonSlug/$legSlug/schedule/': typeof SeasonSlugLegSlugScheduleIndexRoute
  '/$seasonSlug/$legSlug/standings/': typeof SeasonSlugLegSlugStandingsIndexRoute
  '/$seasonSlug/$legSlug/stats/': typeof SeasonSlugLegSlugStatsIndexRoute
  '/$seasonSlug/$legSlug/videos/': typeof SeasonSlugLegSlugVideosIndexRoute
  '/$seasonSlug/$legSlug/voting/': typeof SeasonSlugLegSlugVotingIndexRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures': typeof SeasonSlugLegSlugClubsClubSlugFixturesRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug/stats': typeof SeasonSlugLegSlugClubsClubSlugStatsRoute
  '/$seasonSlug/$legSlug/quiz/$quizId/leaderboard': typeof SeasonSlugLegSlugQuizQuizIdLeaderboardRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h': typeof SeasonSlugLegSlugScheduleFixtureIdH2hRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups': typeof SeasonSlugLegSlugScheduleFixtureIdLineupsRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/stats': typeof SeasonSlugLegSlugScheduleFixtureIdStatsRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug/': typeof SeasonSlugLegSlugClubsClubSlugIndexRoute
  '/$seasonSlug/$legSlug/quiz/$quizId/': typeof SeasonSlugLegSlugQuizQuizIdIndexRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/': typeof SeasonSlugLegSlugScheduleFixtureIdIndexRoute
  '/$seasonSlug/$legSlug/videos/$videoId/': typeof SeasonSlugLegSlugVideosVideoIdIndexRoute
  '/$seasonSlug/$legSlug/voting/$voteId/': typeof SeasonSlugLegSlugVotingVoteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$seasonSlug/$legSlug'
    | '/register'
    | '/request-password'
    | '/reset-password'
    | '/verify'
    | '/$seasonSlug/$legSlug/'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId'
    | '/$seasonSlug/$legSlug/clubs/'
    | '/$seasonSlug/$legSlug/gallery/'
    | '/$seasonSlug/$legSlug/quiz/'
    | '/$seasonSlug/$legSlug/schedule/'
    | '/$seasonSlug/$legSlug/standings/'
    | '/$seasonSlug/$legSlug/stats/'
    | '/$seasonSlug/$legSlug/videos/'
    | '/$seasonSlug/$legSlug/voting/'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
    | '/$seasonSlug/$legSlug/quiz/$quizId/leaderboard'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/stats'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug/'
    | '/$seasonSlug/$legSlug/quiz/$quizId/'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/'
    | '/$seasonSlug/$legSlug/videos/$videoId/'
    | '/$seasonSlug/$legSlug/voting/$voteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/request-password'
    | '/reset-password'
    | '/verify'
    | '/$seasonSlug/$legSlug'
    | '/$seasonSlug/$legSlug/clubs'
    | '/$seasonSlug/$legSlug/gallery'
    | '/$seasonSlug/$legSlug/quiz'
    | '/$seasonSlug/$legSlug/schedule'
    | '/$seasonSlug/$legSlug/standings'
    | '/$seasonSlug/$legSlug/stats'
    | '/$seasonSlug/$legSlug/videos'
    | '/$seasonSlug/$legSlug/voting'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
    | '/$seasonSlug/$legSlug/quiz/$quizId/leaderboard'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/stats'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug'
    | '/$seasonSlug/$legSlug/quiz/$quizId'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId'
    | '/$seasonSlug/$legSlug/videos/$videoId'
    | '/$seasonSlug/$legSlug/voting/$voteId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/$seasonSlug/$legSlug'
    | '/_auth/register'
    | '/_auth/request-password'
    | '/_auth/reset-password'
    | '/_auth/verify'
    | '/$seasonSlug/$legSlug/'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId'
    | '/$seasonSlug/$legSlug/clubs/'
    | '/$seasonSlug/$legSlug/gallery/'
    | '/$seasonSlug/$legSlug/quiz/'
    | '/$seasonSlug/$legSlug/schedule/'
    | '/$seasonSlug/$legSlug/standings/'
    | '/$seasonSlug/$legSlug/stats/'
    | '/$seasonSlug/$legSlug/videos/'
    | '/$seasonSlug/$legSlug/voting/'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
    | '/$seasonSlug/$legSlug/quiz/$quizId/leaderboard'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/stats'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug/'
    | '/$seasonSlug/$legSlug/quiz/$quizId/'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/'
    | '/$seasonSlug/$legSlug/videos/$videoId/'
    | '/$seasonSlug/$legSlug/voting/$voteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SeasonSlugLegSlugRouteRoute: typeof SeasonSlugLegSlugRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/request-password': {
      id: '/_auth/request-password'
      path: '/request-password'
      fullPath: '/request-password'
      preLoaderRoute: typeof AuthRequestPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/$seasonSlug/$legSlug': {
      id: '/$seasonSlug/$legSlug'
      path: '/$seasonSlug/$legSlug'
      fullPath: '/$seasonSlug/$legSlug'
      preLoaderRoute: typeof SeasonSlugLegSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$seasonSlug/$legSlug/': {
      id: '/$seasonSlug/$legSlug/'
      path: '/'
      fullPath: '/$seasonSlug/$legSlug/'
      preLoaderRoute: typeof SeasonSlugLegSlugIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/voting/': {
      id: '/$seasonSlug/$legSlug/voting/'
      path: '/voting'
      fullPath: '/$seasonSlug/$legSlug/voting/'
      preLoaderRoute: typeof SeasonSlugLegSlugVotingIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/videos/': {
      id: '/$seasonSlug/$legSlug/videos/'
      path: '/videos'
      fullPath: '/$seasonSlug/$legSlug/videos/'
      preLoaderRoute: typeof SeasonSlugLegSlugVideosIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/stats/': {
      id: '/$seasonSlug/$legSlug/stats/'
      path: '/stats'
      fullPath: '/$seasonSlug/$legSlug/stats/'
      preLoaderRoute: typeof SeasonSlugLegSlugStatsIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/standings/': {
      id: '/$seasonSlug/$legSlug/standings/'
      path: '/standings'
      fullPath: '/$seasonSlug/$legSlug/standings/'
      preLoaderRoute: typeof SeasonSlugLegSlugStandingsIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/schedule/': {
      id: '/$seasonSlug/$legSlug/schedule/'
      path: '/schedule'
      fullPath: '/$seasonSlug/$legSlug/schedule/'
      preLoaderRoute: typeof SeasonSlugLegSlugScheduleIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/quiz/': {
      id: '/$seasonSlug/$legSlug/quiz/'
      path: '/quiz'
      fullPath: '/$seasonSlug/$legSlug/quiz/'
      preLoaderRoute: typeof SeasonSlugLegSlugQuizIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/gallery/': {
      id: '/$seasonSlug/$legSlug/gallery/'
      path: '/gallery'
      fullPath: '/$seasonSlug/$legSlug/gallery/'
      preLoaderRoute: typeof SeasonSlugLegSlugGalleryIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/clubs/': {
      id: '/$seasonSlug/$legSlug/clubs/'
      path: '/clubs'
      fullPath: '/$seasonSlug/$legSlug/clubs/'
      preLoaderRoute: typeof SeasonSlugLegSlugClubsIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/schedule/$fixtureId': {
      id: '/$seasonSlug/$legSlug/schedule/$fixtureId'
      path: '/schedule/$fixtureId'
      fullPath: '/$seasonSlug/$legSlug/schedule/$fixtureId'
      preLoaderRoute: typeof SeasonSlugLegSlugScheduleFixtureIdRouteRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/clubs/$clubSlug': {
      id: '/$seasonSlug/$legSlug/clubs/$clubSlug'
      path: '/clubs/$clubSlug'
      fullPath: '/$seasonSlug/$legSlug/clubs/$clubSlug'
      preLoaderRoute: typeof SeasonSlugLegSlugClubsClubSlugRouteRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/voting/$voteId/': {
      id: '/$seasonSlug/$legSlug/voting/$voteId/'
      path: '/voting/$voteId'
      fullPath: '/$seasonSlug/$legSlug/voting/$voteId/'
      preLoaderRoute: typeof SeasonSlugLegSlugVotingVoteIdIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/videos/$videoId/': {
      id: '/$seasonSlug/$legSlug/videos/$videoId/'
      path: '/videos/$videoId'
      fullPath: '/$seasonSlug/$legSlug/videos/$videoId/'
      preLoaderRoute: typeof SeasonSlugLegSlugVideosVideoIdIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/schedule/$fixtureId/': {
      id: '/$seasonSlug/$legSlug/schedule/$fixtureId/'
      path: '/'
      fullPath: '/$seasonSlug/$legSlug/schedule/$fixtureId/'
      preLoaderRoute: typeof SeasonSlugLegSlugScheduleFixtureIdIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugScheduleFixtureIdRouteRoute
    }
    '/$seasonSlug/$legSlug/quiz/$quizId/': {
      id: '/$seasonSlug/$legSlug/quiz/$quizId/'
      path: '/quiz/$quizId'
      fullPath: '/$seasonSlug/$legSlug/quiz/$quizId/'
      preLoaderRoute: typeof SeasonSlugLegSlugQuizQuizIdIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/clubs/$clubSlug/': {
      id: '/$seasonSlug/$legSlug/clubs/$clubSlug/'
      path: '/'
      fullPath: '/$seasonSlug/$legSlug/clubs/$clubSlug/'
      preLoaderRoute: typeof SeasonSlugLegSlugClubsClubSlugIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugClubsClubSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/schedule/$fixtureId/stats': {
      id: '/$seasonSlug/$legSlug/schedule/$fixtureId/stats'
      path: '/stats'
      fullPath: '/$seasonSlug/$legSlug/schedule/$fixtureId/stats'
      preLoaderRoute: typeof SeasonSlugLegSlugScheduleFixtureIdStatsRouteImport
      parentRoute: typeof SeasonSlugLegSlugScheduleFixtureIdRouteRoute
    }
    '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups': {
      id: '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups'
      path: '/lineups'
      fullPath: '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups'
      preLoaderRoute: typeof SeasonSlugLegSlugScheduleFixtureIdLineupsRouteImport
      parentRoute: typeof SeasonSlugLegSlugScheduleFixtureIdRouteRoute
    }
    '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h': {
      id: '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h'
      path: '/h2h'
      fullPath: '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h'
      preLoaderRoute: typeof SeasonSlugLegSlugScheduleFixtureIdH2hRouteImport
      parentRoute: typeof SeasonSlugLegSlugScheduleFixtureIdRouteRoute
    }
    '/$seasonSlug/$legSlug/quiz/$quizId/leaderboard': {
      id: '/$seasonSlug/$legSlug/quiz/$quizId/leaderboard'
      path: '/quiz/$quizId/leaderboard'
      fullPath: '/$seasonSlug/$legSlug/quiz/$quizId/leaderboard'
      preLoaderRoute: typeof SeasonSlugLegSlugQuizQuizIdLeaderboardRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/clubs/$clubSlug/stats': {
      id: '/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
      path: '/stats'
      fullPath: '/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
      preLoaderRoute: typeof SeasonSlugLegSlugClubsClubSlugStatsRouteImport
      parentRoute: typeof SeasonSlugLegSlugClubsClubSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures': {
      id: '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'
      path: '/fixtures'
      fullPath: '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'
      preLoaderRoute: typeof SeasonSlugLegSlugClubsClubSlugFixturesRouteImport
      parentRoute: typeof SeasonSlugLegSlugClubsClubSlugRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthRequestPasswordRoute: typeof AuthRequestPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthRegisterRoute: AuthRegisterRoute,
  AuthRequestPasswordRoute: AuthRequestPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface SeasonSlugLegSlugClubsClubSlugRouteRouteChildren {
  SeasonSlugLegSlugClubsClubSlugFixturesRoute: typeof SeasonSlugLegSlugClubsClubSlugFixturesRoute
  SeasonSlugLegSlugClubsClubSlugStatsRoute: typeof SeasonSlugLegSlugClubsClubSlugStatsRoute
  SeasonSlugLegSlugClubsClubSlugIndexRoute: typeof SeasonSlugLegSlugClubsClubSlugIndexRoute
}

const SeasonSlugLegSlugClubsClubSlugRouteRouteChildren: SeasonSlugLegSlugClubsClubSlugRouteRouteChildren =
  {
    SeasonSlugLegSlugClubsClubSlugFixturesRoute:
      SeasonSlugLegSlugClubsClubSlugFixturesRoute,
    SeasonSlugLegSlugClubsClubSlugStatsRoute:
      SeasonSlugLegSlugClubsClubSlugStatsRoute,
    SeasonSlugLegSlugClubsClubSlugIndexRoute:
      SeasonSlugLegSlugClubsClubSlugIndexRoute,
  }

const SeasonSlugLegSlugClubsClubSlugRouteRouteWithChildren =
  SeasonSlugLegSlugClubsClubSlugRouteRoute._addFileChildren(
    SeasonSlugLegSlugClubsClubSlugRouteRouteChildren,
  )

interface SeasonSlugLegSlugScheduleFixtureIdRouteRouteChildren {
  SeasonSlugLegSlugScheduleFixtureIdH2hRoute: typeof SeasonSlugLegSlugScheduleFixtureIdH2hRoute
  SeasonSlugLegSlugScheduleFixtureIdLineupsRoute: typeof SeasonSlugLegSlugScheduleFixtureIdLineupsRoute
  SeasonSlugLegSlugScheduleFixtureIdStatsRoute: typeof SeasonSlugLegSlugScheduleFixtureIdStatsRoute
  SeasonSlugLegSlugScheduleFixtureIdIndexRoute: typeof SeasonSlugLegSlugScheduleFixtureIdIndexRoute
}

const SeasonSlugLegSlugScheduleFixtureIdRouteRouteChildren: SeasonSlugLegSlugScheduleFixtureIdRouteRouteChildren =
  {
    SeasonSlugLegSlugScheduleFixtureIdH2hRoute:
      SeasonSlugLegSlugScheduleFixtureIdH2hRoute,
    SeasonSlugLegSlugScheduleFixtureIdLineupsRoute:
      SeasonSlugLegSlugScheduleFixtureIdLineupsRoute,
    SeasonSlugLegSlugScheduleFixtureIdStatsRoute:
      SeasonSlugLegSlugScheduleFixtureIdStatsRoute,
    SeasonSlugLegSlugScheduleFixtureIdIndexRoute:
      SeasonSlugLegSlugScheduleFixtureIdIndexRoute,
  }

const SeasonSlugLegSlugScheduleFixtureIdRouteRouteWithChildren =
  SeasonSlugLegSlugScheduleFixtureIdRouteRoute._addFileChildren(
    SeasonSlugLegSlugScheduleFixtureIdRouteRouteChildren,
  )

interface SeasonSlugLegSlugRouteRouteChildren {
  SeasonSlugLegSlugIndexRoute: typeof SeasonSlugLegSlugIndexRoute
  SeasonSlugLegSlugClubsClubSlugRouteRoute: typeof SeasonSlugLegSlugClubsClubSlugRouteRouteWithChildren
  SeasonSlugLegSlugScheduleFixtureIdRouteRoute: typeof SeasonSlugLegSlugScheduleFixtureIdRouteRouteWithChildren
  SeasonSlugLegSlugClubsIndexRoute: typeof SeasonSlugLegSlugClubsIndexRoute
  SeasonSlugLegSlugGalleryIndexRoute: typeof SeasonSlugLegSlugGalleryIndexRoute
  SeasonSlugLegSlugQuizIndexRoute: typeof SeasonSlugLegSlugQuizIndexRoute
  SeasonSlugLegSlugScheduleIndexRoute: typeof SeasonSlugLegSlugScheduleIndexRoute
  SeasonSlugLegSlugStandingsIndexRoute: typeof SeasonSlugLegSlugStandingsIndexRoute
  SeasonSlugLegSlugStatsIndexRoute: typeof SeasonSlugLegSlugStatsIndexRoute
  SeasonSlugLegSlugVideosIndexRoute: typeof SeasonSlugLegSlugVideosIndexRoute
  SeasonSlugLegSlugVotingIndexRoute: typeof SeasonSlugLegSlugVotingIndexRoute
  SeasonSlugLegSlugQuizQuizIdLeaderboardRoute: typeof SeasonSlugLegSlugQuizQuizIdLeaderboardRoute
  SeasonSlugLegSlugQuizQuizIdIndexRoute: typeof SeasonSlugLegSlugQuizQuizIdIndexRoute
  SeasonSlugLegSlugVideosVideoIdIndexRoute: typeof SeasonSlugLegSlugVideosVideoIdIndexRoute
  SeasonSlugLegSlugVotingVoteIdIndexRoute: typeof SeasonSlugLegSlugVotingVoteIdIndexRoute
}

const SeasonSlugLegSlugRouteRouteChildren: SeasonSlugLegSlugRouteRouteChildren =
  {
    SeasonSlugLegSlugIndexRoute: SeasonSlugLegSlugIndexRoute,
    SeasonSlugLegSlugClubsClubSlugRouteRoute:
      SeasonSlugLegSlugClubsClubSlugRouteRouteWithChildren,
    SeasonSlugLegSlugScheduleFixtureIdRouteRoute:
      SeasonSlugLegSlugScheduleFixtureIdRouteRouteWithChildren,
    SeasonSlugLegSlugClubsIndexRoute: SeasonSlugLegSlugClubsIndexRoute,
    SeasonSlugLegSlugGalleryIndexRoute: SeasonSlugLegSlugGalleryIndexRoute,
    SeasonSlugLegSlugQuizIndexRoute: SeasonSlugLegSlugQuizIndexRoute,
    SeasonSlugLegSlugScheduleIndexRoute: SeasonSlugLegSlugScheduleIndexRoute,
    SeasonSlugLegSlugStandingsIndexRoute: SeasonSlugLegSlugStandingsIndexRoute,
    SeasonSlugLegSlugStatsIndexRoute: SeasonSlugLegSlugStatsIndexRoute,
    SeasonSlugLegSlugVideosIndexRoute: SeasonSlugLegSlugVideosIndexRoute,
    SeasonSlugLegSlugVotingIndexRoute: SeasonSlugLegSlugVotingIndexRoute,
    SeasonSlugLegSlugQuizQuizIdLeaderboardRoute:
      SeasonSlugLegSlugQuizQuizIdLeaderboardRoute,
    SeasonSlugLegSlugQuizQuizIdIndexRoute:
      SeasonSlugLegSlugQuizQuizIdIndexRoute,
    SeasonSlugLegSlugVideosVideoIdIndexRoute:
      SeasonSlugLegSlugVideosVideoIdIndexRoute,
    SeasonSlugLegSlugVotingVoteIdIndexRoute:
      SeasonSlugLegSlugVotingVoteIdIndexRoute,
  }

const SeasonSlugLegSlugRouteRouteWithChildren =
  SeasonSlugLegSlugRouteRoute._addFileChildren(
    SeasonSlugLegSlugRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SeasonSlugLegSlugRouteRoute: SeasonSlugLegSlugRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
