/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeasonSlugLegSlugRouteRouteImport } from './routes/$seasonSlug/$legSlug/route'
import { Route as SeasonSlugLegSlugIndexRouteImport } from './routes/$seasonSlug/$legSlug/index'
import { Route as SeasonSlugLegSlugStandingsIndexRouteImport } from './routes/$seasonSlug/$legSlug/standings/index'
import { Route as SeasonSlugLegSlugScheduleIndexRouteImport } from './routes/$seasonSlug/$legSlug/schedule/index'
import { Route as SeasonSlugLegSlugClubsIndexRouteImport } from './routes/$seasonSlug/$legSlug/clubs/index'
import { Route as SeasonSlugLegSlugScheduleFixtureIdRouteRouteImport } from './routes/$seasonSlug/$legSlug/schedule/$fixtureId/route'
import { Route as SeasonSlugLegSlugClubsClubSlugRouteRouteImport } from './routes/$seasonSlug/$legSlug/clubs/$clubSlug/route'
import { Route as SeasonSlugLegSlugScheduleFixtureIdIndexRouteImport } from './routes/$seasonSlug/$legSlug/schedule/$fixtureId/index'
import { Route as SeasonSlugLegSlugClubsClubSlugIndexRouteImport } from './routes/$seasonSlug/$legSlug/clubs/$clubSlug/index'
import { Route as SeasonSlugLegSlugScheduleFixtureIdStatsRouteImport } from './routes/$seasonSlug/$legSlug/schedule/$fixtureId/stats'
import { Route as SeasonSlugLegSlugScheduleFixtureIdLineupsRouteImport } from './routes/$seasonSlug/$legSlug/schedule/$fixtureId/lineups'
import { Route as SeasonSlugLegSlugScheduleFixtureIdH2hRouteImport } from './routes/$seasonSlug/$legSlug/schedule/$fixtureId/h2h'
import { Route as SeasonSlugLegSlugClubsClubSlugStatsRouteImport } from './routes/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
import { Route as SeasonSlugLegSlugClubsClubSlugFixturesRouteImport } from './routes/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonSlugLegSlugRouteRoute = SeasonSlugLegSlugRouteRouteImport.update({
  id: '/$seasonSlug/$legSlug',
  path: '/$seasonSlug/$legSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonSlugLegSlugIndexRoute = SeasonSlugLegSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeasonSlugLegSlugRouteRoute,
} as any)
const SeasonSlugLegSlugStandingsIndexRoute =
  SeasonSlugLegSlugStandingsIndexRouteImport.update({
    id: '/standings/',
    path: '/standings/',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugScheduleIndexRoute =
  SeasonSlugLegSlugScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugClubsIndexRoute =
  SeasonSlugLegSlugClubsIndexRouteImport.update({
    id: '/clubs/',
    path: '/clubs/',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugScheduleFixtureIdRouteRoute =
  SeasonSlugLegSlugScheduleFixtureIdRouteRouteImport.update({
    id: '/schedule/$fixtureId',
    path: '/schedule/$fixtureId',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugClubsClubSlugRouteRoute =
  SeasonSlugLegSlugClubsClubSlugRouteRouteImport.update({
    id: '/clubs/$clubSlug',
    path: '/clubs/$clubSlug',
    getParentRoute: () => SeasonSlugLegSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugScheduleFixtureIdIndexRoute =
  SeasonSlugLegSlugScheduleFixtureIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SeasonSlugLegSlugScheduleFixtureIdRouteRoute,
  } as any)
const SeasonSlugLegSlugClubsClubSlugIndexRoute =
  SeasonSlugLegSlugClubsClubSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SeasonSlugLegSlugClubsClubSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugScheduleFixtureIdStatsRoute =
  SeasonSlugLegSlugScheduleFixtureIdStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => SeasonSlugLegSlugScheduleFixtureIdRouteRoute,
  } as any)
const SeasonSlugLegSlugScheduleFixtureIdLineupsRoute =
  SeasonSlugLegSlugScheduleFixtureIdLineupsRouteImport.update({
    id: '/lineups',
    path: '/lineups',
    getParentRoute: () => SeasonSlugLegSlugScheduleFixtureIdRouteRoute,
  } as any)
const SeasonSlugLegSlugScheduleFixtureIdH2hRoute =
  SeasonSlugLegSlugScheduleFixtureIdH2hRouteImport.update({
    id: '/h2h',
    path: '/h2h',
    getParentRoute: () => SeasonSlugLegSlugScheduleFixtureIdRouteRoute,
  } as any)
const SeasonSlugLegSlugClubsClubSlugStatsRoute =
  SeasonSlugLegSlugClubsClubSlugStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => SeasonSlugLegSlugClubsClubSlugRouteRoute,
  } as any)
const SeasonSlugLegSlugClubsClubSlugFixturesRoute =
  SeasonSlugLegSlugClubsClubSlugFixturesRouteImport.update({
    id: '/fixtures',
    path: '/fixtures',
    getParentRoute: () => SeasonSlugLegSlugClubsClubSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$seasonSlug/$legSlug': typeof SeasonSlugLegSlugRouteRouteWithChildren
  '/$seasonSlug/$legSlug/': typeof SeasonSlugLegSlugIndexRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug': typeof SeasonSlugLegSlugClubsClubSlugRouteRouteWithChildren
  '/$seasonSlug/$legSlug/schedule/$fixtureId': typeof SeasonSlugLegSlugScheduleFixtureIdRouteRouteWithChildren
  '/$seasonSlug/$legSlug/clubs/': typeof SeasonSlugLegSlugClubsIndexRoute
  '/$seasonSlug/$legSlug/schedule/': typeof SeasonSlugLegSlugScheduleIndexRoute
  '/$seasonSlug/$legSlug/standings/': typeof SeasonSlugLegSlugStandingsIndexRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures': typeof SeasonSlugLegSlugClubsClubSlugFixturesRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug/stats': typeof SeasonSlugLegSlugClubsClubSlugStatsRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h': typeof SeasonSlugLegSlugScheduleFixtureIdH2hRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups': typeof SeasonSlugLegSlugScheduleFixtureIdLineupsRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/stats': typeof SeasonSlugLegSlugScheduleFixtureIdStatsRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug/': typeof SeasonSlugLegSlugClubsClubSlugIndexRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/': typeof SeasonSlugLegSlugScheduleFixtureIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$seasonSlug/$legSlug': typeof SeasonSlugLegSlugIndexRoute
  '/$seasonSlug/$legSlug/clubs': typeof SeasonSlugLegSlugClubsIndexRoute
  '/$seasonSlug/$legSlug/schedule': typeof SeasonSlugLegSlugScheduleIndexRoute
  '/$seasonSlug/$legSlug/standings': typeof SeasonSlugLegSlugStandingsIndexRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures': typeof SeasonSlugLegSlugClubsClubSlugFixturesRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug/stats': typeof SeasonSlugLegSlugClubsClubSlugStatsRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h': typeof SeasonSlugLegSlugScheduleFixtureIdH2hRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups': typeof SeasonSlugLegSlugScheduleFixtureIdLineupsRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/stats': typeof SeasonSlugLegSlugScheduleFixtureIdStatsRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug': typeof SeasonSlugLegSlugClubsClubSlugIndexRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId': typeof SeasonSlugLegSlugScheduleFixtureIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$seasonSlug/$legSlug': typeof SeasonSlugLegSlugRouteRouteWithChildren
  '/$seasonSlug/$legSlug/': typeof SeasonSlugLegSlugIndexRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug': typeof SeasonSlugLegSlugClubsClubSlugRouteRouteWithChildren
  '/$seasonSlug/$legSlug/schedule/$fixtureId': typeof SeasonSlugLegSlugScheduleFixtureIdRouteRouteWithChildren
  '/$seasonSlug/$legSlug/clubs/': typeof SeasonSlugLegSlugClubsIndexRoute
  '/$seasonSlug/$legSlug/schedule/': typeof SeasonSlugLegSlugScheduleIndexRoute
  '/$seasonSlug/$legSlug/standings/': typeof SeasonSlugLegSlugStandingsIndexRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures': typeof SeasonSlugLegSlugClubsClubSlugFixturesRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug/stats': typeof SeasonSlugLegSlugClubsClubSlugStatsRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h': typeof SeasonSlugLegSlugScheduleFixtureIdH2hRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups': typeof SeasonSlugLegSlugScheduleFixtureIdLineupsRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/stats': typeof SeasonSlugLegSlugScheduleFixtureIdStatsRoute
  '/$seasonSlug/$legSlug/clubs/$clubSlug/': typeof SeasonSlugLegSlugClubsClubSlugIndexRoute
  '/$seasonSlug/$legSlug/schedule/$fixtureId/': typeof SeasonSlugLegSlugScheduleFixtureIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$seasonSlug/$legSlug'
    | '/$seasonSlug/$legSlug/'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId'
    | '/$seasonSlug/$legSlug/clubs/'
    | '/$seasonSlug/$legSlug/schedule/'
    | '/$seasonSlug/$legSlug/standings/'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/stats'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug/'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$seasonSlug/$legSlug'
    | '/$seasonSlug/$legSlug/clubs'
    | '/$seasonSlug/$legSlug/schedule'
    | '/$seasonSlug/$legSlug/standings'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/stats'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId'
  id:
    | '__root__'
    | '/'
    | '/$seasonSlug/$legSlug'
    | '/$seasonSlug/$legSlug/'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId'
    | '/$seasonSlug/$legSlug/clubs/'
    | '/$seasonSlug/$legSlug/schedule/'
    | '/$seasonSlug/$legSlug/standings/'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/stats'
    | '/$seasonSlug/$legSlug/clubs/$clubSlug/'
    | '/$seasonSlug/$legSlug/schedule/$fixtureId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeasonSlugLegSlugRouteRoute: typeof SeasonSlugLegSlugRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$seasonSlug/$legSlug': {
      id: '/$seasonSlug/$legSlug'
      path: '/$seasonSlug/$legSlug'
      fullPath: '/$seasonSlug/$legSlug'
      preLoaderRoute: typeof SeasonSlugLegSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$seasonSlug/$legSlug/': {
      id: '/$seasonSlug/$legSlug/'
      path: '/'
      fullPath: '/$seasonSlug/$legSlug/'
      preLoaderRoute: typeof SeasonSlugLegSlugIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/standings/': {
      id: '/$seasonSlug/$legSlug/standings/'
      path: '/standings'
      fullPath: '/$seasonSlug/$legSlug/standings/'
      preLoaderRoute: typeof SeasonSlugLegSlugStandingsIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/schedule/': {
      id: '/$seasonSlug/$legSlug/schedule/'
      path: '/schedule'
      fullPath: '/$seasonSlug/$legSlug/schedule/'
      preLoaderRoute: typeof SeasonSlugLegSlugScheduleIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/clubs/': {
      id: '/$seasonSlug/$legSlug/clubs/'
      path: '/clubs'
      fullPath: '/$seasonSlug/$legSlug/clubs/'
      preLoaderRoute: typeof SeasonSlugLegSlugClubsIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/schedule/$fixtureId': {
      id: '/$seasonSlug/$legSlug/schedule/$fixtureId'
      path: '/schedule/$fixtureId'
      fullPath: '/$seasonSlug/$legSlug/schedule/$fixtureId'
      preLoaderRoute: typeof SeasonSlugLegSlugScheduleFixtureIdRouteRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/clubs/$clubSlug': {
      id: '/$seasonSlug/$legSlug/clubs/$clubSlug'
      path: '/clubs/$clubSlug'
      fullPath: '/$seasonSlug/$legSlug/clubs/$clubSlug'
      preLoaderRoute: typeof SeasonSlugLegSlugClubsClubSlugRouteRouteImport
      parentRoute: typeof SeasonSlugLegSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/schedule/$fixtureId/': {
      id: '/$seasonSlug/$legSlug/schedule/$fixtureId/'
      path: '/'
      fullPath: '/$seasonSlug/$legSlug/schedule/$fixtureId/'
      preLoaderRoute: typeof SeasonSlugLegSlugScheduleFixtureIdIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugScheduleFixtureIdRouteRoute
    }
    '/$seasonSlug/$legSlug/clubs/$clubSlug/': {
      id: '/$seasonSlug/$legSlug/clubs/$clubSlug/'
      path: '/'
      fullPath: '/$seasonSlug/$legSlug/clubs/$clubSlug/'
      preLoaderRoute: typeof SeasonSlugLegSlugClubsClubSlugIndexRouteImport
      parentRoute: typeof SeasonSlugLegSlugClubsClubSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/schedule/$fixtureId/stats': {
      id: '/$seasonSlug/$legSlug/schedule/$fixtureId/stats'
      path: '/stats'
      fullPath: '/$seasonSlug/$legSlug/schedule/$fixtureId/stats'
      preLoaderRoute: typeof SeasonSlugLegSlugScheduleFixtureIdStatsRouteImport
      parentRoute: typeof SeasonSlugLegSlugScheduleFixtureIdRouteRoute
    }
    '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups': {
      id: '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups'
      path: '/lineups'
      fullPath: '/$seasonSlug/$legSlug/schedule/$fixtureId/lineups'
      preLoaderRoute: typeof SeasonSlugLegSlugScheduleFixtureIdLineupsRouteImport
      parentRoute: typeof SeasonSlugLegSlugScheduleFixtureIdRouteRoute
    }
    '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h': {
      id: '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h'
      path: '/h2h'
      fullPath: '/$seasonSlug/$legSlug/schedule/$fixtureId/h2h'
      preLoaderRoute: typeof SeasonSlugLegSlugScheduleFixtureIdH2hRouteImport
      parentRoute: typeof SeasonSlugLegSlugScheduleFixtureIdRouteRoute
    }
    '/$seasonSlug/$legSlug/clubs/$clubSlug/stats': {
      id: '/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
      path: '/stats'
      fullPath: '/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
      preLoaderRoute: typeof SeasonSlugLegSlugClubsClubSlugStatsRouteImport
      parentRoute: typeof SeasonSlugLegSlugClubsClubSlugRouteRoute
    }
    '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures': {
      id: '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'
      path: '/fixtures'
      fullPath: '/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'
      preLoaderRoute: typeof SeasonSlugLegSlugClubsClubSlugFixturesRouteImport
      parentRoute: typeof SeasonSlugLegSlugClubsClubSlugRouteRoute
    }
  }
}

interface SeasonSlugLegSlugClubsClubSlugRouteRouteChildren {
  SeasonSlugLegSlugClubsClubSlugFixturesRoute: typeof SeasonSlugLegSlugClubsClubSlugFixturesRoute
  SeasonSlugLegSlugClubsClubSlugStatsRoute: typeof SeasonSlugLegSlugClubsClubSlugStatsRoute
  SeasonSlugLegSlugClubsClubSlugIndexRoute: typeof SeasonSlugLegSlugClubsClubSlugIndexRoute
}

const SeasonSlugLegSlugClubsClubSlugRouteRouteChildren: SeasonSlugLegSlugClubsClubSlugRouteRouteChildren =
  {
    SeasonSlugLegSlugClubsClubSlugFixturesRoute:
      SeasonSlugLegSlugClubsClubSlugFixturesRoute,
    SeasonSlugLegSlugClubsClubSlugStatsRoute:
      SeasonSlugLegSlugClubsClubSlugStatsRoute,
    SeasonSlugLegSlugClubsClubSlugIndexRoute:
      SeasonSlugLegSlugClubsClubSlugIndexRoute,
  }

const SeasonSlugLegSlugClubsClubSlugRouteRouteWithChildren =
  SeasonSlugLegSlugClubsClubSlugRouteRoute._addFileChildren(
    SeasonSlugLegSlugClubsClubSlugRouteRouteChildren,
  )

interface SeasonSlugLegSlugScheduleFixtureIdRouteRouteChildren {
  SeasonSlugLegSlugScheduleFixtureIdH2hRoute: typeof SeasonSlugLegSlugScheduleFixtureIdH2hRoute
  SeasonSlugLegSlugScheduleFixtureIdLineupsRoute: typeof SeasonSlugLegSlugScheduleFixtureIdLineupsRoute
  SeasonSlugLegSlugScheduleFixtureIdStatsRoute: typeof SeasonSlugLegSlugScheduleFixtureIdStatsRoute
  SeasonSlugLegSlugScheduleFixtureIdIndexRoute: typeof SeasonSlugLegSlugScheduleFixtureIdIndexRoute
}

const SeasonSlugLegSlugScheduleFixtureIdRouteRouteChildren: SeasonSlugLegSlugScheduleFixtureIdRouteRouteChildren =
  {
    SeasonSlugLegSlugScheduleFixtureIdH2hRoute:
      SeasonSlugLegSlugScheduleFixtureIdH2hRoute,
    SeasonSlugLegSlugScheduleFixtureIdLineupsRoute:
      SeasonSlugLegSlugScheduleFixtureIdLineupsRoute,
    SeasonSlugLegSlugScheduleFixtureIdStatsRoute:
      SeasonSlugLegSlugScheduleFixtureIdStatsRoute,
    SeasonSlugLegSlugScheduleFixtureIdIndexRoute:
      SeasonSlugLegSlugScheduleFixtureIdIndexRoute,
  }

const SeasonSlugLegSlugScheduleFixtureIdRouteRouteWithChildren =
  SeasonSlugLegSlugScheduleFixtureIdRouteRoute._addFileChildren(
    SeasonSlugLegSlugScheduleFixtureIdRouteRouteChildren,
  )

interface SeasonSlugLegSlugRouteRouteChildren {
  SeasonSlugLegSlugIndexRoute: typeof SeasonSlugLegSlugIndexRoute
  SeasonSlugLegSlugClubsClubSlugRouteRoute: typeof SeasonSlugLegSlugClubsClubSlugRouteRouteWithChildren
  SeasonSlugLegSlugScheduleFixtureIdRouteRoute: typeof SeasonSlugLegSlugScheduleFixtureIdRouteRouteWithChildren
  SeasonSlugLegSlugClubsIndexRoute: typeof SeasonSlugLegSlugClubsIndexRoute
  SeasonSlugLegSlugScheduleIndexRoute: typeof SeasonSlugLegSlugScheduleIndexRoute
  SeasonSlugLegSlugStandingsIndexRoute: typeof SeasonSlugLegSlugStandingsIndexRoute
}

const SeasonSlugLegSlugRouteRouteChildren: SeasonSlugLegSlugRouteRouteChildren =
  {
    SeasonSlugLegSlugIndexRoute: SeasonSlugLegSlugIndexRoute,
    SeasonSlugLegSlugClubsClubSlugRouteRoute:
      SeasonSlugLegSlugClubsClubSlugRouteRouteWithChildren,
    SeasonSlugLegSlugScheduleFixtureIdRouteRoute:
      SeasonSlugLegSlugScheduleFixtureIdRouteRouteWithChildren,
    SeasonSlugLegSlugClubsIndexRoute: SeasonSlugLegSlugClubsIndexRoute,
    SeasonSlugLegSlugScheduleIndexRoute: SeasonSlugLegSlugScheduleIndexRoute,
    SeasonSlugLegSlugStandingsIndexRoute: SeasonSlugLegSlugStandingsIndexRoute,
  }

const SeasonSlugLegSlugRouteRouteWithChildren =
  SeasonSlugLegSlugRouteRoute._addFileChildren(
    SeasonSlugLegSlugRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeasonSlugLegSlugRouteRoute: SeasonSlugLegSlugRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
