/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteRouteImport } from './routes/_site/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRequestPasswordRouteImport } from './routes/_auth/request-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as SiteVotingIndexRouteImport } from './routes/_site/voting/index'
import { Route as SiteQuizIndexRouteImport } from './routes/_site/quiz/index'
import { Route as SiteGalleryIndexRouteImport } from './routes/_site/gallery/index'
import { Route as SiteVotingVoteIdIndexRouteImport } from './routes/_site/voting/$voteId/index'
import { Route as SiteQuizQuizIdIndexRouteImport } from './routes/_site/quiz/$quizId/index'
import { Route as SiteGalleryImageIdIndexRouteImport } from './routes/_site/gallery/$imageId/index'
import { Route as SiteQuizQuizIdLeaderboardRouteImport } from './routes/_site/quiz/$quizId/leaderboard'
import { Route as SiteLeagueSlugSeasonSlugScheduleRouteRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/schedule/route'
import { Route as SiteLeagueSlugSeasonSlugLegSlugRouteRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/$legSlug/route'
import { Route as SiteLeagueSlugSeasonSlugScheduleIndexRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/schedule/index'
import { Route as SiteLeagueSlugSeasonSlugGalleryIndexRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/gallery/index'
import { Route as SiteLeagueSlugSeasonSlugLegSlugIndexRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/$legSlug/index'
import { Route as SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/route'
import { Route as SiteLeagueSlugSeasonSlugScheduleFixtureIdIndexRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/index'
import { Route as SiteLeagueSlugSeasonSlugLegSlugVideosIndexRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/$legSlug/videos/index'
import { Route as SiteLeagueSlugSeasonSlugLegSlugStatsIndexRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/$legSlug/stats/index'
import { Route as SiteLeagueSlugSeasonSlugLegSlugStandingsIndexRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/$legSlug/standings/index'
import { Route as SiteLeagueSlugSeasonSlugLegSlugClubsIndexRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/index'
import { Route as SiteLeagueSlugSeasonSlugScheduleFixtureIdStatsRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/stats'
import { Route as SiteLeagueSlugSeasonSlugScheduleFixtureIdLineupsRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/lineups'
import { Route as SiteLeagueSlugSeasonSlugScheduleFixtureIdH2hRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/h2h'
import { Route as SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/route'
import { Route as SiteLeagueSlugSeasonSlugLegSlugVideosVideoIdIndexRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/$legSlug/videos/$videoId/index'
import { Route as SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugIndexRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/index'
import { Route as SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdTeamsRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/teams'
import { Route as SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdPlayersRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/players'
import { Route as SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugStatsRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
import { Route as SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugFixturesRouteImport } from './routes/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'

const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRequestPasswordRoute = AuthRequestPasswordRouteImport.update({
  id: '/request-password',
  path: '/request-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const SiteVotingIndexRoute = SiteVotingIndexRouteImport.update({
  id: '/voting/',
  path: '/voting/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteQuizIndexRoute = SiteQuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteGalleryIndexRoute = SiteGalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteVotingVoteIdIndexRoute = SiteVotingVoteIdIndexRouteImport.update({
  id: '/voting/$voteId/',
  path: '/voting/$voteId/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteQuizQuizIdIndexRoute = SiteQuizQuizIdIndexRouteImport.update({
  id: '/quiz/$quizId/',
  path: '/quiz/$quizId/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteGalleryImageIdIndexRoute = SiteGalleryImageIdIndexRouteImport.update({
  id: '/gallery/$imageId/',
  path: '/gallery/$imageId/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteQuizQuizIdLeaderboardRoute =
  SiteQuizQuizIdLeaderboardRouteImport.update({
    id: '/quiz/$quizId/leaderboard',
    path: '/quiz/$quizId/leaderboard',
    getParentRoute: () => SiteRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugScheduleRouteRoute =
  SiteLeagueSlugSeasonSlugScheduleRouteRouteImport.update({
    id: '/$leagueSlug/$seasonSlug/schedule',
    path: '/$leagueSlug/$seasonSlug/schedule',
    getParentRoute: () => SiteRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugLegSlugRouteRoute =
  SiteLeagueSlugSeasonSlugLegSlugRouteRouteImport.update({
    id: '/$leagueSlug/$seasonSlug/$legSlug',
    path: '/$leagueSlug/$seasonSlug/$legSlug',
    getParentRoute: () => SiteRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugScheduleIndexRoute =
  SiteLeagueSlugSeasonSlugScheduleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SiteLeagueSlugSeasonSlugScheduleRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugGalleryIndexRoute =
  SiteLeagueSlugSeasonSlugGalleryIndexRouteImport.update({
    id: '/$leagueSlug/$seasonSlug/gallery/',
    path: '/$leagueSlug/$seasonSlug/gallery/',
    getParentRoute: () => SiteRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugLegSlugIndexRoute =
  SiteLeagueSlugSeasonSlugLegSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SiteLeagueSlugSeasonSlugLegSlugRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRoute =
  SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRouteImport.update({
    id: '/$fixtureId',
    path: '/$fixtureId',
    getParentRoute: () => SiteLeagueSlugSeasonSlugScheduleRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugScheduleFixtureIdIndexRoute =
  SiteLeagueSlugSeasonSlugScheduleFixtureIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugLegSlugVideosIndexRoute =
  SiteLeagueSlugSeasonSlugLegSlugVideosIndexRouteImport.update({
    id: '/videos/',
    path: '/videos/',
    getParentRoute: () => SiteLeagueSlugSeasonSlugLegSlugRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugLegSlugStatsIndexRoute =
  SiteLeagueSlugSeasonSlugLegSlugStatsIndexRouteImport.update({
    id: '/stats/',
    path: '/stats/',
    getParentRoute: () => SiteLeagueSlugSeasonSlugLegSlugRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugLegSlugStandingsIndexRoute =
  SiteLeagueSlugSeasonSlugLegSlugStandingsIndexRouteImport.update({
    id: '/standings/',
    path: '/standings/',
    getParentRoute: () => SiteLeagueSlugSeasonSlugLegSlugRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugLegSlugClubsIndexRoute =
  SiteLeagueSlugSeasonSlugLegSlugClubsIndexRouteImport.update({
    id: '/clubs/',
    path: '/clubs/',
    getParentRoute: () => SiteLeagueSlugSeasonSlugLegSlugRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugScheduleFixtureIdStatsRoute =
  SiteLeagueSlugSeasonSlugScheduleFixtureIdStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugScheduleFixtureIdLineupsRoute =
  SiteLeagueSlugSeasonSlugScheduleFixtureIdLineupsRouteImport.update({
    id: '/lineups',
    path: '/lineups',
    getParentRoute: () => SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugScheduleFixtureIdH2hRoute =
  SiteLeagueSlugSeasonSlugScheduleFixtureIdH2hRouteImport.update({
    id: '/h2h',
    path: '/h2h',
    getParentRoute: () => SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRoute =
  SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRouteImport.update({
    id: '/clubs/$clubSlug',
    path: '/clubs/$clubSlug',
    getParentRoute: () => SiteLeagueSlugSeasonSlugLegSlugRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugLegSlugVideosVideoIdIndexRoute =
  SiteLeagueSlugSeasonSlugLegSlugVideosVideoIdIndexRouteImport.update({
    id: '/videos/$videoId/',
    path: '/videos/$videoId/',
    getParentRoute: () => SiteLeagueSlugSeasonSlugLegSlugRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugIndexRoute =
  SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdTeamsRoute =
  SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdTeamsRouteImport.update({
    id: '/stats/$statsId/teams',
    path: '/stats/$statsId/teams',
    getParentRoute: () => SiteLeagueSlugSeasonSlugLegSlugRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdPlayersRoute =
  SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdPlayersRouteImport.update({
    id: '/stats/$statsId/players',
    path: '/stats/$statsId/players',
    getParentRoute: () => SiteLeagueSlugSeasonSlugLegSlugRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugStatsRoute =
  SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () =>
      SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRoute,
  } as any)
const SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugFixturesRoute =
  SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugFixturesRouteImport.update({
    id: '/fixtures',
    path: '/fixtures',
    getParentRoute: () =>
      SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof AuthRegisterRoute
  '/request-password': typeof AuthRequestPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify': typeof AuthVerifyRoute
  '/gallery/': typeof SiteGalleryIndexRoute
  '/quiz/': typeof SiteQuizIndexRoute
  '/voting/': typeof SiteVotingIndexRoute
  '/$leagueSlug/$seasonSlug/$legSlug': typeof SiteLeagueSlugSeasonSlugLegSlugRouteRouteWithChildren
  '/$leagueSlug/$seasonSlug/schedule': typeof SiteLeagueSlugSeasonSlugScheduleRouteRouteWithChildren
  '/quiz/$quizId/leaderboard': typeof SiteQuizQuizIdLeaderboardRoute
  '/gallery/$imageId/': typeof SiteGalleryImageIdIndexRoute
  '/quiz/$quizId/': typeof SiteQuizQuizIdIndexRoute
  '/voting/$voteId/': typeof SiteVotingVoteIdIndexRoute
  '/$leagueSlug/$seasonSlug/schedule/$fixtureId': typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRouteWithChildren
  '/$leagueSlug/$seasonSlug/$legSlug/': typeof SiteLeagueSlugSeasonSlugLegSlugIndexRoute
  '/$leagueSlug/$seasonSlug/gallery/': typeof SiteLeagueSlugSeasonSlugGalleryIndexRoute
  '/$leagueSlug/$seasonSlug/schedule/': typeof SiteLeagueSlugSeasonSlugScheduleIndexRoute
  '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug': typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRouteWithChildren
  '/$leagueSlug/$seasonSlug/schedule/$fixtureId/h2h': typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdH2hRoute
  '/$leagueSlug/$seasonSlug/schedule/$fixtureId/lineups': typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdLineupsRoute
  '/$leagueSlug/$seasonSlug/schedule/$fixtureId/stats': typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdStatsRoute
  '/$leagueSlug/$seasonSlug/$legSlug/clubs/': typeof SiteLeagueSlugSeasonSlugLegSlugClubsIndexRoute
  '/$leagueSlug/$seasonSlug/$legSlug/standings/': typeof SiteLeagueSlugSeasonSlugLegSlugStandingsIndexRoute
  '/$leagueSlug/$seasonSlug/$legSlug/stats/': typeof SiteLeagueSlugSeasonSlugLegSlugStatsIndexRoute
  '/$leagueSlug/$seasonSlug/$legSlug/videos/': typeof SiteLeagueSlugSeasonSlugLegSlugVideosIndexRoute
  '/$leagueSlug/$seasonSlug/schedule/$fixtureId/': typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdIndexRoute
  '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures': typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugFixturesRoute
  '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/stats': typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugStatsRoute
  '/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/players': typeof SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdPlayersRoute
  '/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/teams': typeof SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdTeamsRoute
  '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/': typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugIndexRoute
  '/$leagueSlug/$seasonSlug/$legSlug/videos/$videoId/': typeof SiteLeagueSlugSeasonSlugLegSlugVideosVideoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof AuthRegisterRoute
  '/request-password': typeof AuthRequestPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify': typeof AuthVerifyRoute
  '/gallery': typeof SiteGalleryIndexRoute
  '/quiz': typeof SiteQuizIndexRoute
  '/voting': typeof SiteVotingIndexRoute
  '/quiz/$quizId/leaderboard': typeof SiteQuizQuizIdLeaderboardRoute
  '/gallery/$imageId': typeof SiteGalleryImageIdIndexRoute
  '/quiz/$quizId': typeof SiteQuizQuizIdIndexRoute
  '/voting/$voteId': typeof SiteVotingVoteIdIndexRoute
  '/$leagueSlug/$seasonSlug/$legSlug': typeof SiteLeagueSlugSeasonSlugLegSlugIndexRoute
  '/$leagueSlug/$seasonSlug/gallery': typeof SiteLeagueSlugSeasonSlugGalleryIndexRoute
  '/$leagueSlug/$seasonSlug/schedule': typeof SiteLeagueSlugSeasonSlugScheduleIndexRoute
  '/$leagueSlug/$seasonSlug/schedule/$fixtureId/h2h': typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdH2hRoute
  '/$leagueSlug/$seasonSlug/schedule/$fixtureId/lineups': typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdLineupsRoute
  '/$leagueSlug/$seasonSlug/schedule/$fixtureId/stats': typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdStatsRoute
  '/$leagueSlug/$seasonSlug/$legSlug/clubs': typeof SiteLeagueSlugSeasonSlugLegSlugClubsIndexRoute
  '/$leagueSlug/$seasonSlug/$legSlug/standings': typeof SiteLeagueSlugSeasonSlugLegSlugStandingsIndexRoute
  '/$leagueSlug/$seasonSlug/$legSlug/stats': typeof SiteLeagueSlugSeasonSlugLegSlugStatsIndexRoute
  '/$leagueSlug/$seasonSlug/$legSlug/videos': typeof SiteLeagueSlugSeasonSlugLegSlugVideosIndexRoute
  '/$leagueSlug/$seasonSlug/schedule/$fixtureId': typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdIndexRoute
  '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures': typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugFixturesRoute
  '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/stats': typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugStatsRoute
  '/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/players': typeof SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdPlayersRoute
  '/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/teams': typeof SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdTeamsRoute
  '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug': typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugIndexRoute
  '/$leagueSlug/$seasonSlug/$legSlug/videos/$videoId': typeof SiteLeagueSlugSeasonSlugLegSlugVideosVideoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_site': typeof SiteRouteRouteWithChildren
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/request-password': typeof AuthRequestPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/_site/gallery/': typeof SiteGalleryIndexRoute
  '/_site/quiz/': typeof SiteQuizIndexRoute
  '/_site/voting/': typeof SiteVotingIndexRoute
  '/_site/$leagueSlug/$seasonSlug/$legSlug': typeof SiteLeagueSlugSeasonSlugLegSlugRouteRouteWithChildren
  '/_site/$leagueSlug/$seasonSlug/schedule': typeof SiteLeagueSlugSeasonSlugScheduleRouteRouteWithChildren
  '/_site/quiz/$quizId/leaderboard': typeof SiteQuizQuizIdLeaderboardRoute
  '/_site/gallery/$imageId/': typeof SiteGalleryImageIdIndexRoute
  '/_site/quiz/$quizId/': typeof SiteQuizQuizIdIndexRoute
  '/_site/voting/$voteId/': typeof SiteVotingVoteIdIndexRoute
  '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId': typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRouteWithChildren
  '/_site/$leagueSlug/$seasonSlug/$legSlug/': typeof SiteLeagueSlugSeasonSlugLegSlugIndexRoute
  '/_site/$leagueSlug/$seasonSlug/gallery/': typeof SiteLeagueSlugSeasonSlugGalleryIndexRoute
  '/_site/$leagueSlug/$seasonSlug/schedule/': typeof SiteLeagueSlugSeasonSlugScheduleIndexRoute
  '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug': typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRouteWithChildren
  '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/h2h': typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdH2hRoute
  '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/lineups': typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdLineupsRoute
  '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/stats': typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdStatsRoute
  '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/': typeof SiteLeagueSlugSeasonSlugLegSlugClubsIndexRoute
  '/_site/$leagueSlug/$seasonSlug/$legSlug/standings/': typeof SiteLeagueSlugSeasonSlugLegSlugStandingsIndexRoute
  '/_site/$leagueSlug/$seasonSlug/$legSlug/stats/': typeof SiteLeagueSlugSeasonSlugLegSlugStatsIndexRoute
  '/_site/$leagueSlug/$seasonSlug/$legSlug/videos/': typeof SiteLeagueSlugSeasonSlugLegSlugVideosIndexRoute
  '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/': typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdIndexRoute
  '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures': typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugFixturesRoute
  '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/stats': typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugStatsRoute
  '/_site/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/players': typeof SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdPlayersRoute
  '/_site/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/teams': typeof SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdTeamsRoute
  '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/': typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugIndexRoute
  '/_site/$leagueSlug/$seasonSlug/$legSlug/videos/$videoId/': typeof SiteLeagueSlugSeasonSlugLegSlugVideosVideoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/request-password'
    | '/reset-password'
    | '/verify'
    | '/gallery/'
    | '/quiz/'
    | '/voting/'
    | '/$leagueSlug/$seasonSlug/$legSlug'
    | '/$leagueSlug/$seasonSlug/schedule'
    | '/quiz/$quizId/leaderboard'
    | '/gallery/$imageId/'
    | '/quiz/$quizId/'
    | '/voting/$voteId/'
    | '/$leagueSlug/$seasonSlug/schedule/$fixtureId'
    | '/$leagueSlug/$seasonSlug/$legSlug/'
    | '/$leagueSlug/$seasonSlug/gallery/'
    | '/$leagueSlug/$seasonSlug/schedule/'
    | '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug'
    | '/$leagueSlug/$seasonSlug/schedule/$fixtureId/h2h'
    | '/$leagueSlug/$seasonSlug/schedule/$fixtureId/lineups'
    | '/$leagueSlug/$seasonSlug/schedule/$fixtureId/stats'
    | '/$leagueSlug/$seasonSlug/$legSlug/clubs/'
    | '/$leagueSlug/$seasonSlug/$legSlug/standings/'
    | '/$leagueSlug/$seasonSlug/$legSlug/stats/'
    | '/$leagueSlug/$seasonSlug/$legSlug/videos/'
    | '/$leagueSlug/$seasonSlug/schedule/$fixtureId/'
    | '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'
    | '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
    | '/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/players'
    | '/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/teams'
    | '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/'
    | '/$leagueSlug/$seasonSlug/$legSlug/videos/$videoId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/request-password'
    | '/reset-password'
    | '/verify'
    | '/gallery'
    | '/quiz'
    | '/voting'
    | '/quiz/$quizId/leaderboard'
    | '/gallery/$imageId'
    | '/quiz/$quizId'
    | '/voting/$voteId'
    | '/$leagueSlug/$seasonSlug/$legSlug'
    | '/$leagueSlug/$seasonSlug/gallery'
    | '/$leagueSlug/$seasonSlug/schedule'
    | '/$leagueSlug/$seasonSlug/schedule/$fixtureId/h2h'
    | '/$leagueSlug/$seasonSlug/schedule/$fixtureId/lineups'
    | '/$leagueSlug/$seasonSlug/schedule/$fixtureId/stats'
    | '/$leagueSlug/$seasonSlug/$legSlug/clubs'
    | '/$leagueSlug/$seasonSlug/$legSlug/standings'
    | '/$leagueSlug/$seasonSlug/$legSlug/stats'
    | '/$leagueSlug/$seasonSlug/$legSlug/videos'
    | '/$leagueSlug/$seasonSlug/schedule/$fixtureId'
    | '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'
    | '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
    | '/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/players'
    | '/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/teams'
    | '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug'
    | '/$leagueSlug/$seasonSlug/$legSlug/videos/$videoId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_site'
    | '/_auth/register'
    | '/_auth/request-password'
    | '/_auth/reset-password'
    | '/_auth/verify'
    | '/_site/gallery/'
    | '/_site/quiz/'
    | '/_site/voting/'
    | '/_site/$leagueSlug/$seasonSlug/$legSlug'
    | '/_site/$leagueSlug/$seasonSlug/schedule'
    | '/_site/quiz/$quizId/leaderboard'
    | '/_site/gallery/$imageId/'
    | '/_site/quiz/$quizId/'
    | '/_site/voting/$voteId/'
    | '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId'
    | '/_site/$leagueSlug/$seasonSlug/$legSlug/'
    | '/_site/$leagueSlug/$seasonSlug/gallery/'
    | '/_site/$leagueSlug/$seasonSlug/schedule/'
    | '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug'
    | '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/h2h'
    | '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/lineups'
    | '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/stats'
    | '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/'
    | '/_site/$leagueSlug/$seasonSlug/$legSlug/standings/'
    | '/_site/$leagueSlug/$seasonSlug/$legSlug/stats/'
    | '/_site/$leagueSlug/$seasonSlug/$legSlug/videos/'
    | '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/'
    | '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'
    | '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
    | '/_site/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/players'
    | '/_site/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/teams'
    | '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/'
    | '/_site/$leagueSlug/$seasonSlug/$legSlug/videos/$videoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/request-password': {
      id: '/_auth/request-password'
      path: '/request-password'
      fullPath: '/request-password'
      preLoaderRoute: typeof AuthRequestPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_site/voting/': {
      id: '/_site/voting/'
      path: '/voting'
      fullPath: '/voting/'
      preLoaderRoute: typeof SiteVotingIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/quiz/': {
      id: '/_site/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof SiteQuizIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/gallery/': {
      id: '/_site/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof SiteGalleryIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/voting/$voteId/': {
      id: '/_site/voting/$voteId/'
      path: '/voting/$voteId'
      fullPath: '/voting/$voteId/'
      preLoaderRoute: typeof SiteVotingVoteIdIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/quiz/$quizId/': {
      id: '/_site/quiz/$quizId/'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId/'
      preLoaderRoute: typeof SiteQuizQuizIdIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/gallery/$imageId/': {
      id: '/_site/gallery/$imageId/'
      path: '/gallery/$imageId'
      fullPath: '/gallery/$imageId/'
      preLoaderRoute: typeof SiteGalleryImageIdIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/quiz/$quizId/leaderboard': {
      id: '/_site/quiz/$quizId/leaderboard'
      path: '/quiz/$quizId/leaderboard'
      fullPath: '/quiz/$quizId/leaderboard'
      preLoaderRoute: typeof SiteQuizQuizIdLeaderboardRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/schedule': {
      id: '/_site/$leagueSlug/$seasonSlug/schedule'
      path: '/$leagueSlug/$seasonSlug/schedule'
      fullPath: '/$leagueSlug/$seasonSlug/schedule'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugScheduleRouteRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/$legSlug': {
      id: '/_site/$leagueSlug/$seasonSlug/$legSlug'
      path: '/$leagueSlug/$seasonSlug/$legSlug'
      fullPath: '/$leagueSlug/$seasonSlug/$legSlug'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugLegSlugRouteRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/schedule/': {
      id: '/_site/$leagueSlug/$seasonSlug/schedule/'
      path: '/'
      fullPath: '/$leagueSlug/$seasonSlug/schedule/'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugScheduleIndexRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugScheduleRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/gallery/': {
      id: '/_site/$leagueSlug/$seasonSlug/gallery/'
      path: '/$leagueSlug/$seasonSlug/gallery'
      fullPath: '/$leagueSlug/$seasonSlug/gallery/'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugGalleryIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/$legSlug/': {
      id: '/_site/$leagueSlug/$seasonSlug/$legSlug/'
      path: '/'
      fullPath: '/$leagueSlug/$seasonSlug/$legSlug/'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugLegSlugIndexRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugLegSlugRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId': {
      id: '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId'
      path: '/$fixtureId'
      fullPath: '/$leagueSlug/$seasonSlug/schedule/$fixtureId'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugScheduleRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/': {
      id: '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/'
      path: '/'
      fullPath: '/$leagueSlug/$seasonSlug/schedule/$fixtureId/'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdIndexRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/$legSlug/videos/': {
      id: '/_site/$leagueSlug/$seasonSlug/$legSlug/videos/'
      path: '/videos'
      fullPath: '/$leagueSlug/$seasonSlug/$legSlug/videos/'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugLegSlugVideosIndexRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugLegSlugRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/$legSlug/stats/': {
      id: '/_site/$leagueSlug/$seasonSlug/$legSlug/stats/'
      path: '/stats'
      fullPath: '/$leagueSlug/$seasonSlug/$legSlug/stats/'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugLegSlugStatsIndexRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugLegSlugRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/$legSlug/standings/': {
      id: '/_site/$leagueSlug/$seasonSlug/$legSlug/standings/'
      path: '/standings'
      fullPath: '/$leagueSlug/$seasonSlug/$legSlug/standings/'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugLegSlugStandingsIndexRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugLegSlugRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/': {
      id: '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/'
      path: '/clubs'
      fullPath: '/$leagueSlug/$seasonSlug/$legSlug/clubs/'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugLegSlugClubsIndexRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugLegSlugRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/stats': {
      id: '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/stats'
      path: '/stats'
      fullPath: '/$leagueSlug/$seasonSlug/schedule/$fixtureId/stats'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdStatsRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/lineups': {
      id: '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/lineups'
      path: '/lineups'
      fullPath: '/$leagueSlug/$seasonSlug/schedule/$fixtureId/lineups'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdLineupsRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/h2h': {
      id: '/_site/$leagueSlug/$seasonSlug/schedule/$fixtureId/h2h'
      path: '/h2h'
      fullPath: '/$leagueSlug/$seasonSlug/schedule/$fixtureId/h2h'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdH2hRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug': {
      id: '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug'
      path: '/clubs/$clubSlug'
      fullPath: '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugLegSlugRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/$legSlug/videos/$videoId/': {
      id: '/_site/$leagueSlug/$seasonSlug/$legSlug/videos/$videoId/'
      path: '/videos/$videoId'
      fullPath: '/$leagueSlug/$seasonSlug/$legSlug/videos/$videoId/'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugLegSlugVideosVideoIdIndexRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugLegSlugRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/': {
      id: '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/'
      path: '/'
      fullPath: '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugIndexRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/teams': {
      id: '/_site/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/teams'
      path: '/stats/$statsId/teams'
      fullPath: '/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/teams'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdTeamsRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugLegSlugRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/players': {
      id: '/_site/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/players'
      path: '/stats/$statsId/players'
      fullPath: '/$leagueSlug/$seasonSlug/$legSlug/stats/$statsId/players'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdPlayersRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugLegSlugRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/stats': {
      id: '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
      path: '/stats'
      fullPath: '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/stats'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugStatsRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRoute
    }
    '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures': {
      id: '/_site/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'
      path: '/fixtures'
      fullPath: '/$leagueSlug/$seasonSlug/$legSlug/clubs/$clubSlug/fixtures'
      preLoaderRoute: typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugFixturesRouteImport
      parentRoute: typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthRequestPasswordRoute: typeof AuthRequestPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthRegisterRoute: AuthRegisterRoute,
  AuthRequestPasswordRoute: AuthRequestPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRouteChildren {
  SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugFixturesRoute: typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugFixturesRoute
  SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugStatsRoute: typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugStatsRoute
  SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugIndexRoute: typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugIndexRoute
}

const SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRouteChildren: SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRouteChildren =
  {
    SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugFixturesRoute:
      SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugFixturesRoute,
    SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugStatsRoute:
      SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugStatsRoute,
    SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugIndexRoute:
      SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugIndexRoute,
  }

const SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRouteWithChildren =
  SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRoute._addFileChildren(
    SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRouteChildren,
  )

interface SiteLeagueSlugSeasonSlugLegSlugRouteRouteChildren {
  SiteLeagueSlugSeasonSlugLegSlugIndexRoute: typeof SiteLeagueSlugSeasonSlugLegSlugIndexRoute
  SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRoute: typeof SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRouteWithChildren
  SiteLeagueSlugSeasonSlugLegSlugClubsIndexRoute: typeof SiteLeagueSlugSeasonSlugLegSlugClubsIndexRoute
  SiteLeagueSlugSeasonSlugLegSlugStandingsIndexRoute: typeof SiteLeagueSlugSeasonSlugLegSlugStandingsIndexRoute
  SiteLeagueSlugSeasonSlugLegSlugStatsIndexRoute: typeof SiteLeagueSlugSeasonSlugLegSlugStatsIndexRoute
  SiteLeagueSlugSeasonSlugLegSlugVideosIndexRoute: typeof SiteLeagueSlugSeasonSlugLegSlugVideosIndexRoute
  SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdPlayersRoute: typeof SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdPlayersRoute
  SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdTeamsRoute: typeof SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdTeamsRoute
  SiteLeagueSlugSeasonSlugLegSlugVideosVideoIdIndexRoute: typeof SiteLeagueSlugSeasonSlugLegSlugVideosVideoIdIndexRoute
}

const SiteLeagueSlugSeasonSlugLegSlugRouteRouteChildren: SiteLeagueSlugSeasonSlugLegSlugRouteRouteChildren =
  {
    SiteLeagueSlugSeasonSlugLegSlugIndexRoute:
      SiteLeagueSlugSeasonSlugLegSlugIndexRoute,
    SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRoute:
      SiteLeagueSlugSeasonSlugLegSlugClubsClubSlugRouteRouteWithChildren,
    SiteLeagueSlugSeasonSlugLegSlugClubsIndexRoute:
      SiteLeagueSlugSeasonSlugLegSlugClubsIndexRoute,
    SiteLeagueSlugSeasonSlugLegSlugStandingsIndexRoute:
      SiteLeagueSlugSeasonSlugLegSlugStandingsIndexRoute,
    SiteLeagueSlugSeasonSlugLegSlugStatsIndexRoute:
      SiteLeagueSlugSeasonSlugLegSlugStatsIndexRoute,
    SiteLeagueSlugSeasonSlugLegSlugVideosIndexRoute:
      SiteLeagueSlugSeasonSlugLegSlugVideosIndexRoute,
    SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdPlayersRoute:
      SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdPlayersRoute,
    SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdTeamsRoute:
      SiteLeagueSlugSeasonSlugLegSlugStatsStatsIdTeamsRoute,
    SiteLeagueSlugSeasonSlugLegSlugVideosVideoIdIndexRoute:
      SiteLeagueSlugSeasonSlugLegSlugVideosVideoIdIndexRoute,
  }

const SiteLeagueSlugSeasonSlugLegSlugRouteRouteWithChildren =
  SiteLeagueSlugSeasonSlugLegSlugRouteRoute._addFileChildren(
    SiteLeagueSlugSeasonSlugLegSlugRouteRouteChildren,
  )

interface SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRouteChildren {
  SiteLeagueSlugSeasonSlugScheduleFixtureIdH2hRoute: typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdH2hRoute
  SiteLeagueSlugSeasonSlugScheduleFixtureIdLineupsRoute: typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdLineupsRoute
  SiteLeagueSlugSeasonSlugScheduleFixtureIdStatsRoute: typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdStatsRoute
  SiteLeagueSlugSeasonSlugScheduleFixtureIdIndexRoute: typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdIndexRoute
}

const SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRouteChildren: SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRouteChildren =
  {
    SiteLeagueSlugSeasonSlugScheduleFixtureIdH2hRoute:
      SiteLeagueSlugSeasonSlugScheduleFixtureIdH2hRoute,
    SiteLeagueSlugSeasonSlugScheduleFixtureIdLineupsRoute:
      SiteLeagueSlugSeasonSlugScheduleFixtureIdLineupsRoute,
    SiteLeagueSlugSeasonSlugScheduleFixtureIdStatsRoute:
      SiteLeagueSlugSeasonSlugScheduleFixtureIdStatsRoute,
    SiteLeagueSlugSeasonSlugScheduleFixtureIdIndexRoute:
      SiteLeagueSlugSeasonSlugScheduleFixtureIdIndexRoute,
  }

const SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRouteWithChildren =
  SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRoute._addFileChildren(
    SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRouteChildren,
  )

interface SiteLeagueSlugSeasonSlugScheduleRouteRouteChildren {
  SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRoute: typeof SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRouteWithChildren
  SiteLeagueSlugSeasonSlugScheduleIndexRoute: typeof SiteLeagueSlugSeasonSlugScheduleIndexRoute
}

const SiteLeagueSlugSeasonSlugScheduleRouteRouteChildren: SiteLeagueSlugSeasonSlugScheduleRouteRouteChildren =
  {
    SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRoute:
      SiteLeagueSlugSeasonSlugScheduleFixtureIdRouteRouteWithChildren,
    SiteLeagueSlugSeasonSlugScheduleIndexRoute:
      SiteLeagueSlugSeasonSlugScheduleIndexRoute,
  }

const SiteLeagueSlugSeasonSlugScheduleRouteRouteWithChildren =
  SiteLeagueSlugSeasonSlugScheduleRouteRoute._addFileChildren(
    SiteLeagueSlugSeasonSlugScheduleRouteRouteChildren,
  )

interface SiteRouteRouteChildren {
  SiteGalleryIndexRoute: typeof SiteGalleryIndexRoute
  SiteQuizIndexRoute: typeof SiteQuizIndexRoute
  SiteVotingIndexRoute: typeof SiteVotingIndexRoute
  SiteLeagueSlugSeasonSlugLegSlugRouteRoute: typeof SiteLeagueSlugSeasonSlugLegSlugRouteRouteWithChildren
  SiteLeagueSlugSeasonSlugScheduleRouteRoute: typeof SiteLeagueSlugSeasonSlugScheduleRouteRouteWithChildren
  SiteQuizQuizIdLeaderboardRoute: typeof SiteQuizQuizIdLeaderboardRoute
  SiteGalleryImageIdIndexRoute: typeof SiteGalleryImageIdIndexRoute
  SiteQuizQuizIdIndexRoute: typeof SiteQuizQuizIdIndexRoute
  SiteVotingVoteIdIndexRoute: typeof SiteVotingVoteIdIndexRoute
  SiteLeagueSlugSeasonSlugGalleryIndexRoute: typeof SiteLeagueSlugSeasonSlugGalleryIndexRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteGalleryIndexRoute: SiteGalleryIndexRoute,
  SiteQuizIndexRoute: SiteQuizIndexRoute,
  SiteVotingIndexRoute: SiteVotingIndexRoute,
  SiteLeagueSlugSeasonSlugLegSlugRouteRoute:
    SiteLeagueSlugSeasonSlugLegSlugRouteRouteWithChildren,
  SiteLeagueSlugSeasonSlugScheduleRouteRoute:
    SiteLeagueSlugSeasonSlugScheduleRouteRouteWithChildren,
  SiteQuizQuizIdLeaderboardRoute: SiteQuizQuizIdLeaderboardRoute,
  SiteGalleryImageIdIndexRoute: SiteGalleryImageIdIndexRoute,
  SiteQuizQuizIdIndexRoute: SiteQuizQuizIdIndexRoute,
  SiteVotingVoteIdIndexRoute: SiteVotingVoteIdIndexRoute,
  SiteLeagueSlugSeasonSlugGalleryIndexRoute:
    SiteLeagueSlugSeasonSlugGalleryIndexRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SiteRouteRoute: SiteRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
